version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  orderservice:
    image: sumeriancore/spring-app-rabbit
    container_name: spring-app
    build:
      context: .
    ports:
      - "8081:8080"
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    links:
      - rabbitmq
